postgresql:
  auth:
    database: ps_db
    password: SecurePassword
    username: ps_user
secretStoreCredentials:
  enable: true  
  isStsEnable: false
default:
  image: alex130a/helm-integrator-app:1.0.0
  app_port: 8000
  replicas: 1
  debug: 0