apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://alex-her-1304.github.io/helm-integrator-chart
    targetRevision: 0.8.0
    chart: mychart
    helm:
    parameters:
      - name: postgresql.auth.database
        value: ps_db
      - name: postgresql.auth.password
        value: SecurePassword
      - name: postgresql.auth.username
        value: ps_user
      - name: secretStoreCredentials.enable
        value: true
      - name: secretStoreCredentials.isStsEnable
        value: false
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
